#!/bin/bash
VM=$1
DESTHOST=$2


[ -z "$VM" ] && exit 1
[ -z "$DESTHOST" ] && exit 1
(virsh list --name |grep -w  "$VM") || exit 1
echo "$VM is running here"

DRBDMANAGERESs="`virsh domblklist $VM |grep /dev/drbd/by-res/| perl -pe 's;^.*/dev/drbd/by-res/(.*)/[0-9]+\s*$;$1\n;g'|sort -u`"

for DRBDMANAGERES in $DRBDMANAGERESs; do
  drbdadm net-options --allow-two-primaries=yes $DRBDMANAGERES || exit 1
  echo "allow two primaries is set for disk $DRBDMANAGERES"
done
echo "allow two primaries is set for disks: $DRBDMANAGERESs"

virsh migrate $VM qemu+ssh://$DESTHOST/system --live --p2p --undefinesource --verbose --compressed --auto-converge

for DRBDMANAGERES in $DRBDMANAGERESs; do
  drbdadm net-options --allow-two-primaries=no $DRBDMANAGERES || exit 1
  echo "allow two primaries is unset for disk $DRBDMANAGERES"
done
echo "allow two primaries is unset for disks: $DRBDMANAGERESs"
echo "done"

